// Address of the HelloWorld contract on Sepolia
const CONTRACT_ADDRESS = "0xE913A381F9b5f28eE49E6Fc929Da7C607580C870";

// Minimal ABI automatically generated by Hardhat (read + write)
const ABI = window.HELLOWORLD_ABI;

// Retrieve DOM elements
const connectButton = document.getElementById("connectButton");
const accountDisplay = document.getElementById("accountDisplay");
const readButton = document.getElementById("readButton");
const currentMessageDisplay = document.getElementById("currentMessage");
const updateButton = document.getElementById("updateButton");
const newMessageInput = document.getElementById("newMessageInput");
const txStatus = document.getElementById("txStatus");

let provider;
let signer;
let contract;

// -----------------------------
// 🔌 1. Connect wallet
// -----------------------------
connectButton.onclick = async () => {
  try {
    if (!window.ethereum) {
      alert("MetaMask not detected!");
      return;
    }

    // Request MetaMask connection
    const accounts = await window.ethereum.request({
      method: "eth_requestAccounts",
    });

    const userAddress = accounts[0];
    accountDisplay.textContent = userAddress;

    // Create Ethers v6 provider connected to MetaMask
    provider = new ethers.BrowserProvider(window.ethereum);

    // Signer (for sending transactions)
    signer = await provider.getSigner();

    // Contract instance
    contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);

    alert("Wallet connected!");
  } catch (err) {
    console.error(err);
  }
};

// -----------------------------
// 📖 2. Read the message from the blockchain
// -----------------------------
readButton.onclick = async () => {
  try {
    if (!contract) {
      alert("Connect your wallet first!");
      return;
    }

    const message = await contract.getMessage();
    currentMessageDisplay.textContent = message;
  } catch (err) {
    console.error(err);
  }
};

// -----------------------------
// ✏️ 3. Update the message
// -----------------------------
updateButton.onclick = async () => {
  try {
    if (!contract) {
      alert("Connect your wallet first!");
      return;
    }

    const newMsg = newMessageInput.value.trim();
    if (!newMsg) {
      alert("Message cannot be empty");
      return;
    }

    txStatus.textContent = "⏳ Transaction in progress...";

    // Send the transaction
    const tx = await contract.setMessage(newMsg);
    txStatus.textContent = "⏳ Transaction sent: " + tx.hash;

    // Wait for confirmation
    await tx.wait();
    txStatus.textContent = "✅ Transaction confirmed!";

    // Update the displayed message
    currentMessageDisplay.textContent = await contract.getMessage();
  } catch (err) {
    console.error(err);
    txStatus.textContent = "❌ Transaction error";
  }
};
